### ISSUE TITLE
iconPosition "right" generate warning.

### ISSUE THREAD

**Issue by solshark** [arfedulov/semantic-ui-calendar-react#76]
**Describe the bug**
iconPosition accept only "left" attribute. In fact it works with "right" also but triggers warning:
```
Warning: Failed prop type: Invalid prop `iconPosition` of value `right` supplied to `Input`, expected one of ["left"].
```

**To Reproduce**
1. Embed <TimeInput />
2. Set attribute `iconPosition="right"`
3. See warning in browser console.

**Expected behavior**
No warning triggered.

**Screenshots**

<img width="1049" alt="2019-01-23 14 35 00" src="https://user-images.githubusercontent.com/107233/51607011-2dd52700-1f1c-11e9-85c5-ff310783a6b4.png">

**Dependencies versions**

* semantic-ui-react: 0.84.0
* semantic-ui-css (or any alternative): 2.4.1
* semantic-ui-calendar-react: 0.13.0

**Comment by arfedulov** [comment]
Actually the intention was just to pass `iconPosition` to underlying input element which has only one possible value `"left"`. But icon positioned properly only if `iconPosition` has some value. And here is related issue #74. So yeah, this is a bug.

**Comment by arfedulov** [comment]
fixed in #101

**Comment by abhiphirke** [comment]
Hey, this is really awesome. But I still can't use it because 0.14.2 is not on NPM package yet.  Could you please update the NPM package as well? I am prohibited from installing from the Git repo directly.

**Comment by arfedulov** [comment]
Yeah, just published it.
